version: '3'

services:
  app:
    build: .
    ports:
      - 8080:80
    labels:
      - "traefik.http.routers.api.rule=Host(`test.zzzx.tech`)"
      - "traefik.http.routers.api.service=api@internal"

networks:
  default:
    name: traefik_default
