version: '3'

services:
  app:
    build: .
    ports:
      - 8080:80
    labels:
      - traefik.http.routers.test.rule=Host(`test.zzzx.tech`)
      - traefik.http.services.test.loadbalancer.server.port=80

networks:
  default:
    name: traefik_default
