version: "3"

services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
      # - verdaccio:/verdaccio

networks:
  default:
    name: npm
