version: "3"

services:
  verdaccio:
    image: verdaccio/verdaccio
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
      # - verdaccio:/verdaccio
    labels:
      - traefik.http.routers.verdaccio.rule=Host(`verdaccio.zzzx.tech`)
      - traefik.http.routers.your-service-name.tls=true
      - traefik.http.routers.your-service-name.tls.certresolver=le

networks:
  default:
    name: traefik_default
