version: "3"

services:
  verdaccio:
    image: verdaccio/verdaccio:nightly-master
    ports:
      - '4873:4873'
    volumes:
      - './storage:/verdaccio/storage'
      - './conf:/verdaccio/conf'
      # - verdaccio:/verdaccio
      # labels:
      #   - traefik.http.routers.whoami.rule=Host(``)
      #   - traefik.http.routers.whoami.tls=true
      #   - traefik.http.routers.whoami.tls.certresolver=le

      # networks:
      #   default:
      #     external:
      #       name: traefik_default
